

export const ROUTES = {
    HOME: "/",
    LOGIN: "/login",
    SIGNUP: "/signup",
    FORGOT_PASSWORD: "/forgotpassword",
    PRODUCT_PAGE: "/productpage",
    USE_CASES_PAGE: "/usecases",
    PRIVACY_PAGE: "/privacypage",
    PRIVACY: "/privacy",
    ARTICLE: "/article",
    BLOG_DETAIL: "/blog/:blogId",
    ADD_BLOG: "/addblog",
    BLOGS: "/blogs",
    CALL_TO_ACTIONS: "/calltoactions",
    BETA: "/beta",
    SUBSCRIPTIONS: "/subscriptions",
    SUCCESS: "/success",
    PRICING_PLAN: "/pricing-plan",
    CREDIT_DASHBOARD: "/credit-dashboard",
    CREDIT_ADMIN_DASHBOARD: "/credit-admin-dashboard",
    PURCHASE_CREDITS: "/purchase-credits",
    CREDIT_HISTORY: "/credit-history",
    DASHBOARD: "/dashboard",
    PROFILE: "/profile",
    EXPRESSION_OF_INTEREST: "/eoi",
    WIDGETS: "/widgets",
    CHAT_WIDGET: "/chat-widget",
    SEARCH_WIDGET: "/search-widget",
    DOCUMENTATION: "/documentation",
    CONCEPTUALIZE: "/conceptualize/:conceptId",
    LANDING: "/landing",
    HOME_PAGE: "/homepage",
    IDEALISE_CHAT: "/idealisechat",
    DEVELOP: "/develop",
    CHECKOUT_PLAN: "/checkout/:plan",
    TEST: "/test",
    DEMO: "/byte-demo",
    LEADCAPTURESCREEN: "/intro"
  };
  